### ISSUE TITLE
Relevant paper 

### ISSUE THREAD

**Issue by jadeCurl** [hijkzzz/Awesome-LLM-Strawberry#10]
Hi,

Thank you for organizing and sharing such valuable resources! I would like to recommend a paper titled [Chain of Preference Optimization: Improving Chain-of-Thought Reasoning in LLMs](https://arxiv.org/abs/2406.09136) for inclusion.   In this paper, we perform reasoning using the Tree of Thought (ToT) approach and distill these reasoning processes into the LLM's Chain of Thought (CoT). This method serves as a form of self-reflection & self-improvement , effectively improving the model's ability to handle complex reasoning tasks. 

I hope you might consider adding this paper to your list of recommendations. Thank you!

**Comment by hijkzzz** [comment]
merged
