### ISSUE TITLE
【suggestion】add benchmarks and datasets

### ISSUE THREAD

**Issue by yananchen1989** [hijkzzz/Awesome-LLM-Strawberry#17]
this is just a suggestion that this repo can add datasets and benchmarks, such as openai/gsm8k, lighteval/MATH etc... where CoT format solution is provided. 

As you know, only some datasets have endogenous CoT-like solutions which are valuable for this thread of research. Therefore it would be best to list them in this repo. 

thanks.

**Comment by hijkzzz** [comment]
Thank you for your suggestion. It will be added later.
